# Generated by Django 4.2.6 on 2023-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_change_raw_response_from_dict_to_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativetitle",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="alternativetitle",
            name="type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_vote_average",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_vote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_average",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
